import { writeFileSync } from "node:fs";
import {
  SEED_CATEGORIES, SEED_PRODUCTS, SNEAKER_SIZES, CLOTHING_SIZES, seedSlug, placeholderStock,
} from "../lib/data/seed-catalogue";

const q = (s: string) => `'${s.replace(/'/g, "''")}'`;
const out: string[] = [
  "-- GENERATED by `npm run seed:sql` from lib/data/seed-catalogue.ts. Do not edit by hand.",
  "-- Stock quantities are PLACEHOLDERS. Correct them in /admin before going live.",
  "begin;",
];

for (const c of SEED_CATEGORIES)
  out.push(`insert into categories (slug,name,description,sort_order) values (${q(c.slug)},${q(c.name)},${q(c.description)},${c.sort}) on conflict (slug) do nothing;`);

out.push(`insert into option_sets (category_id,name,values) select id,'size',array[${SNEAKER_SIZES.map(q)}] from categories where slug='sneakers' on conflict do nothing;`);
out.push(`insert into option_sets (category_id,name,values) select id,'size',array[${CLOTHING_SIZES.map(q)}] from categories where slug='clothing' on conflict do nothing;`);

SEED_PRODUCTS.forEach((p, i) => {
  const slug = seedSlug(p);
  const desc =
    p.category === "iphones"
      ? `${p.condition === "pre_owned" ? "Pre-owned" : "Brand new"} ${p.model}. Storage, colour and battery health confirmed on request.`
      : `${p.name}. Sizes and availability are updated live.`;
  out.push(
    `insert into products (slug,name,description,category_id,brand,model,colour,condition,price_cents,featured,published) ` +
    `select ${q(slug)},${q(p.name)},${q(desc)},id,${q(p.brand)},${q(p.model)},${p.colour ? q(p.colour) : "null"},${q(p.condition)},${p.priceRand * 100},${!!p.featured},true from categories where slug=${q(p.category)} on conflict (slug) do nothing;`,
  );
  if (p.imageUrl) {
    out.push(
      `insert into product_images (product_id,url,alt,source,sort_order) ` +
      `select id,${q(p.imageUrl)},${q(`${p.name} product image`)},'own',0 from products ` +
      `where slug=${q(slug)} and not exists (select 1 from product_images where product_id=products.id and url=${q(p.imageUrl)});`,
    );
  }
  const sizes = p.category === "sneakers" ? SNEAKER_SIZES : p.category === "clothing" ? CLOTHING_SIZES : [null];
  sizes.forEach((size, si) => {
    const qty = p.category === "iphones" ? (i % 3 === 0 ? 0 : 1 + (i % 2)) : placeholderStock(i, si);
    const sku = `${slug}${size ? "-" + size.replace(/\s+/g, "").toLowerCase() : ""}`;
    out.push(
      `with v as (insert into product_variants (product_id,sku,size) select id,${q(sku)},${size ? q(size) : "null"} from products where slug=${q(slug)} on conflict (sku) do nothing returning id) ` +
      `insert into inventory (variant_id,quantity) select id,${qty} from v;`,
    );
  });
});
out.push("commit;");
writeFileSync("supabase/seed.sql", out.join("\n") + "\n");
console.log(`seed.sql: ${SEED_PRODUCTS.length} products`);
